# ---------------------------------------------------------------- RESET TIME ----------------------------------------------------------------
from src.timeFns import  toResetTime


RESET_TIME = {
    "Scamacca": toResetTime("Chẵn 18 - Chẵn 38"),
    "Correa": toResetTime("Chẵn 15 - Chẵn 35"),
    "Unal": toResetTime("Chẵn 01 - Chẵn 21"),
    "Anguissa": toResetTime("Chẵn 20 - Chẵn 40"),
    "Awoniyi": toResetTime("Chẵn 06 - Chẵn 26"),
    "Rowe": toResetTime("Chẵn 30 - Chẵn 50"),
    "Guedes": toResetTime("Chẵn 15 - Chẵn 35"),
    "Bravo": toResetTime("Chẵn 00-25"),
    "Sangare": toResetTime("Chẵn 24 - Chẵn 44"),
    "Benítez": toResetTime("Chẵn 31 - Chẵn 51"),
    "Gordon": toResetTime("Chẵn 36 - Chẵn 56"),
    "Matić": toResetTime("Lẻ 54 - Chẵn 14"),
    'Bremer': toResetTime("Chẵn 00-25"),
    'Nunes': toResetTime("Chẵn 56 - Lẻ 16"),
    "Jose": toResetTime("Chẵn 09 - Chẵn 29"),
    "Kampl": toResetTime("Chẵn 30-59"),
    "Chandler": toResetTime("Chẵn 30-59"),
    "Saponara": toResetTime("Chẵn 30-59"),
    "Iwobi": toResetTime("Chẵn 00-25"),
    "Patricio": toResetTime("Chẵn 00-25"),
    "Banega": toResetTime("Chẵn 30-59"),
    "Grifo": toResetTime("Chẵn 30-59"),
    "Anderson": toResetTime("Chẵn 30-59"),
    "Kaka": toResetTime("Chẵn 00-25"),
    "Henry": toResetTime("Chẵn 20-40"),
    "Pirlo": toResetTime("Chẵn 20-40"),
    "Mathu": toResetTime("Chẵn 00-25"),
    "Bergkamp": toResetTime("Chẵn 00-25"),
    "Inaki": toResetTime("Chẵn 30-59"),
    'Suarez': toResetTime("Lẻ 00 - Lẻ 25"),
    "Vieira": toResetTime("Chẵn 15-35"),
    "Xabi Alonso": toResetTime("Chẵn 29-49"),
    "Gerrard": toResetTime("Chẵn 24-45"),
    "Torres": toResetTime("Chẵn 31-51"),
    "Gerrard ITM": toResetTime("Chẵn 00-25"),
    "Herrmann": toResetTime("Chẵn 00-25"),
    "Fekir": toResetTime("Chẵn 00-25"),
    "Inaki": toResetTime("Chẵn 30-59"),
    "Wirtz": toResetTime("Chẵn 55 - Lẻ 15"),
    "Danjuma": toResetTime("Chẵn 22 - Chẵn 42"),
    "Abedi": toResetTime("Lẻ 16 - Lẻ 36"),
    "Xabi Alonso CU": toResetTime("chẳn 56 - lẻ 16"),
    "Antony": toResetTime("Chẵn 44 - Lẻ 04"),
    "Kewell": toResetTime("Lẻ 55 - Chẵn 20"),
    "Cristiano Ronaldo": toResetTime("Chẵn 55 - Lẻ 20"),
    "Iago": toResetTime("Chẵn 10-30"),
    "Kolasinac": toResetTime("Chẵn 00-25"),
    "Kante": toResetTime("Chẵn 00-25"),
    "Sule": toResetTime("Chẵn 17-37"),
    "Adeyemi": toResetTime("Chẵn 41 - Lẻ 01"),
    "Matheus Nunes": toResetTime("Chẵn 52 - Lẻ 16"),
    "Oyarzabal": toResetTime("Chẵn 00-25"),
    "Raul Albiol": toResetTime("Chẵn 00-25"),
    "Faes": toResetTime("Chẵn 00-25"),
    "Illarramendi": toResetTime("Chẵn 34-59"),
    "Navas": toResetTime("Chẵn 30-59"),
    "Fornals": toResetTime("Chẵn 30-59"),
    "Blind": toResetTime("Chẵn 10-30"),
    "Carrasco": toResetTime("Chẵn 40 - Lẻ 01"),
    "Vitinha": toResetTime("Chẵn 55 - Lẻ 23"),
    "Ginola": toResetTime("Lẻ 16 - Lẻ 43"),
    "Diaby": toResetTime("Chẵn 40 - Lẻ 01"),
}