# ---------------------------------------------------------------- RESET TIME ----------------------------------------------------------------
from src.timeFns import  toResetTime


RESET_TIME = {
    "Scamacca": toResetTime("Chẵn 18 - Chẵn 38"),
    "Correa": toResetTime("Chẵn 15 - Chẵn 35"),
    "Unal": toResetTime("Chẵn 01 - Chẵn 21"),
    "Anguissa": toResetTime("Chẵn 20 - Chẵn 40"),
    "Awoniyi": toResetTime("Chẵn 06 - Chẵn 26"),
    "Rowe": toResetTime("Chẵn 30 - Chẵn 50"),
    "Guedes": toResetTime("Chẵn 15 - Chẵn 35"),
    "Milik": toResetTime("Lẻ 59 - Chẵn 19"),
    "Muani": toResetTime("Chẵn 18 - Chẵn 38"),
    "Bravo": toResetTime("Chẵn 00-25"),
    "Sangare": toResetTime("Chẵn 24 - Chẵn 44"),
    "Benítez": toResetTime("Chẵn 31 - Chẵn 51"),
    "Gordon": toResetTime("Chẵn 36 - Chẵn 56"),
    "Matić": toResetTime("Lẻ 54 - Chẵn 14"),
    'Bremer': toResetTime("Chẵn 00-25"),
    'Nunes': toResetTime("Chẵn 56 - Lẻ 16"),
    "Jose": toResetTime("Chẵn 09 - Chẵn 29"),
    "Kampl": toResetTime("Chẵn 30-59"),
    "Chandler": toResetTime("Chẵn 30-59"),
    "Saponara": toResetTime("Chẵn 30-59"),
    "Iwobi": toResetTime("Chẵn 00-25"),
    "Patricio": toResetTime("Chẵn 00-25"),
    "Banega": toResetTime("Chẵn 30-59"),
    "Grifo": toResetTime("Chẵn 30-59"),
    "Anderson": toResetTime("Chẵn 30-59"),
    "Kaka": toResetTime("Chẵn 00-25"),
    "Henry": toResetTime("Chẵn 20-40"),
    "Pirlo": toResetTime("Chẵn 20-40"),
    "Mathu": toResetTime("Chẵn 00-25"),
    "Bergkamp": toResetTime("Chẵn 00-25"),
    "Illarramendi": toResetTime("Chẵn 00-25"),
    "Inaki": toResetTime("Chẵn 30-59"),
    'Suarez': toResetTime("Lẻ 00 - Lẻ 25"),
    "Vieira": toResetTime("Chẵn 15-35"),
    "Xabi Alonso": toResetTime("Chẵn 29-49"),
    "Gerrard": toResetTime("Chẵn 24-45"),
    "Torres": toResetTime("Chẵn 50 - Lẻ 20"),
    "Gerrard ITM": toResetTime("Chẵn 00-25"),
    "Herrmann": toResetTime("Chẵn 00-25"),
    "Fekir": toResetTime("Chẵn 00-25"),
    "Inaki": toResetTime("Chẵn 30-59"),
    "Wirtz": toResetTime("Chẵn 55 - Lẻ 15"),
    "Danjuma": toResetTime("Chẵn 22 - Chẵn 42"),
    "Abedi": toResetTime("Lẻ 16 - Lẻ 36"),
    "Xabi Alonso CU": toResetTime("chẳn 56_lẻ 16"),
    
}